- name: "[kamelGenie]"
  hosts: all
  become: yes
  tasks:
     - name: "[kamelGenie]  -copie des fichier"
       copy:
          src: ./vcs.xml
          dest: /vscjenk.xml

   
  tasks:
     - name: "creation d archive de deploiment"
       command: "tar cf ./roles.tar ./roles"
       delegate_to: 127.0.0.3