- name: "[kamelGenie]"
  hosts: all
  become: yes
#  tasks:
#     - name: "[kamelGenie]  -copie des fichier"
#       copy:
#          src: ./vcs.xml
#          dest: /vscjenk.xml

#  tasks:
#     - name: "izaaaaan"
#       file:
#          path: "/root/tp/projects/app"
#          state: directory
#          mode: '0777'
  tasks:
     - name: "archiage de idea"
       command: "tar cfvz idea.tar.gz ../.idea" 
       delegate_to: 127.0.0.1
           
          
#  tasks:
#     - name: "creation d archive de deploiment"
#       copy:
#          src: ./jenk_roles.tar.gz
#          dest: /root/var/projects
#          
          
#  tasks:
#     - name: "creation automatiqument"
#       unarchive:
#           src: ./jenk_roles.tar.gz
#           dest: /root/tp/projects/app       
#           