- name: "[kamelGenie]"
  hosts: all
  become: yes
#  tasks:
#     - name: "[kamelGenie]  -copie des fichier"
#       copy:
#          src: ./vcs.xml
#          dest: /vscjenk.xml


  tasks:
     - name: "suppression des rep de travail"
       shell: "rm -rf /root/var/projects/*" 
  tasks:
     - name: "creation  de rep de traval"
       file:
          path: "/root/tp/projects/app"
          state: directory
          mode: '0777'       
           
          
  tasks:
     - name: "creation d archive de deploiment"
       copy:
          src: ./jenk_roles.tar.gz
          dest: /root/var/projects/app
          
          
#  tasks:
#     - name: "creation automatiqument"
#       unarchive:
#           src: ./jenk_roles.tar.gz
#           dest: /root/tp/projects/app       
#           